<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net472</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MidiDdsp.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Numerics.Tensors" Version="9.0.0" />
  </ItemGroup>

</Project>
